### ISSUE TITLE
转换qwen模型的时候，提示atten_mask:5 error.

### ISSUE THREAD

**Issue by louwangzhiyuY** [luchangli03/export_llama_to_onnx#10]
odeling_qwen.py:1297: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  self._seq_len_cached = max(2 * seqlen, 16)
C:\Users\ML\.cache\huggingface\modules\transformers_modules\Qwen\Qwen-7B-Chat\218aa3240fd5a5d1e80bb6c47d5d774361913706\modeling_qwen.py:482: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if key_size > self.seq_length and self.use_logn_attn and not self.training:
C:\Users\ML\.cache\huggingface\modules\transformers_modules\Qwen\Qwen-7B-Chat\218aa3240fd5a5d1e80bb6c47d5d774361913706\modeling_qwen.py:502: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if query.size(1) == key_size:
In-place op on output of tensor.shape. See https://pytorch.org/docs/master/onnx.html#avoid-inplace-operations-when-using-tensor-shape-in-tracing-mode
Traceback (most recent call last):
  File "c:\work\AI\directml\export_llama_to_onnx\export_qwen_naive.py", line 173, in <module>
    export_qwen(args)
  File "c:\work\AI\directml\export_llama_to_onnx\export_qwen_naive.py", line 151, in export_qwen
    export_qwen_to_single_onnx(model, config, dtype, args, "qwen_onnx")
  File "c:\work\AI\directml\export_llama_to_onnx\export_qwen_naive.py", line 109, in export_qwen_to_single_onnx
    torch.onnx.export(
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\onnx\utils.py", line 516, in export
    _export(
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\onnx\utils.py", line 1596, in _export
    graph, params_dict, torch_out = _model_to_graph(
                                    ^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\onnx\utils.py", line 1139, in _model_to_graph
    graph = _optimize_graph(
            ^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\onnx\utils.py", line 677, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\onnx\utils.py", line 1940, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\onnx\symbolic_helper.py", line 306, in wrapper
    return fn(g, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\onnx\symbolic_opset14.py", line 197, in scaled_dot_product_attention
    raise ValueError(
ValueError: Unsupported type for attn_mask: 5

**Comment by alphaRGB** [comment]
遇到相同的转换错误

**Comment by BeStrongok** [comment]
同样的错误，请问有大佬解决了吗
