### ISSUE TITLE
转换llama也提示错误。 AttributeError: 'tuple' object has no attribute 'get_usable_length'

### ISSUE THREAD

**Issue by louwangzhiyuY** [luchangli03/export_llama_to_onnx#11]
racerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if output_attentions:
Traceback (most recent call last):
  File "c:\work\AI\directml\export_llama_to_onnx\export_llama_single.py", line 161, in <module>
    export_llama(args)
  File "c:\work\AI\directml\export_llama_to_onnx\export_llama_single.py", line 140, in export_llama
    export_llama_to_single_onnx(model, config, dtype, args, "llama_onnx")
  File "c:\work\AI\directml\export_llama_to_onnx\export_llama_single.py", line 108, in export_llama_to_single_onnx
    torch.onnx.export(
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\onnx\utils.py", line 516, in export
    _export(
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\onnx\utils.py", line 1596, in _export
    graph, params_dict, torch_out = _model_to_graph(
                                    ^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\onnx\utils.py", line 1135, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\onnx\utils.py", line 1011, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\onnx\utils.py", line 915, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\jit\_trace.py", line 1285, in _get_trace_graph
    outs = ONNXTracedModule(
           ^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\jit\_trace.py", line 133, in forward
    graph, out = torch._C._create_graph_by_tracing(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\jit\_trace.py", line 124, in wrapper
    outs.append(self.inner(*trace_inputs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\nn\modules\module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export_llama_single.py", line 30, in forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\nn\modules\module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 796, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
                                                          ^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\torch\nn\modules\module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\AI\directml\export_llama_to_onnx\export.ven\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 701, in forward
    kv_seq_len += past_key_value.get_usable_length(kv_seq_len, self.layer_idx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'get_usable_length'

**Comment by zanilia1016** [comment]
可以降级transformer库，4.32版本的应该没问题
