### ISSUE TITLE
转换QWen-7B错误

### ISSUE THREAD

**Issue by L1-M1ng** [luchangli03/export_llama_to_onnx#12]
您好，我使用您提供的export_qwen_naive.py程序将本地的QWen-7B模型转换成onnx时出现报错：

begin export qwen
/home/mingli/.cache/huggingface/modules/transformers_modules/Qwen-7B/modeling_qwen.py:823: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if batch_size <= 0:
/home/mingli/.cache/huggingface/modules/transformers_modules/Qwen-7B/modeling_qwen.py:848: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  elif kv_seq_len != hidden_states.size()[1]:
/home/mingli/.cache/huggingface/modules/transformers_modules/Qwen-7B/modeling_qwen.py:1308: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if seqlen > self._seq_len_cached or ntk_alpha != self._ntk_alpha_cached:
/home/mingli/.cache/huggingface/modules/transformers_modules/Qwen-7B/modeling_qwen.py:1317: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  self._seq_len_cached = max(2 * seqlen, 16)
Traceback (most recent call last):
  File "/home/mingli/projects/Qwen/qwen2onnx.py", line 199, in <module>
    export_qwen(args)
  File "/home/mingli/projects/Qwen/qwen2onnx.py", line 178, in export_qwen
    export_qwen_to_single_onnx(model, config, dtype, args, "qwen_onnx")
  File "/home/mingli/projects/Qwen/qwen2onnx.py", line 131, in export_qwen_to_single_onnx
    torch.onnx.export(
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/onnx/utils.py", line 1613, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/onnx/utils.py", line 1135, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/onnx/utils.py", line 1011, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/onnx/utils.py", line 915, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/jit/_trace.py", line 1296, in _get_trace_graph
    outs = ONNXTracedModule(
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/jit/_trace.py", line 138, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/jit/_trace.py", line 129, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/mingli/projects/Qwen/qwen2onnx.py", line 23, in forward
    transformer_outputs = self.model.transformer(
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/mingli/.cache/huggingface/modules/transformers_modules/Qwen-7B/modeling_qwen.py", line 909, in forward
    outputs = block(  # 这里调用的是 QWenBlock 的 forward 函数
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/mingli/.cache/huggingface/modules/transformers_modules/Qwen-7B/modeling_qwen.py", line 610, in forward
    attn_outputs = self.attn( # attention
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mingli/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/mingli/.cache/huggingface/modules/transformers_modules/Qwen-7B/modeling_qwen.py", line 464, in forward
    key = (torch.cat((past_key[0], key[0]), dim=2),
RuntimeError: Tensors must have same number of dimensions: got 3 and 4

这好像是kv_cache的shape有误，我想请问在转化过程中kv_cache的初始输入是必须的么？能否只提供input_ids，因为我在本地调用模型进行推理时，transformer的输出只有input_ids，其他为None
推理的代码如下：
`input = tokenizer("hello world", return_tensors="pt")
    
    model = AutoModelForCausalLM.from_pretrained(
        args.model_path, device_map=device, trust_remote_code=True, **dtype_cfg).eval()
 
    pred = model.generate(**input)  # 跑官方的推理 `

不知道我的理解是否正确？

**Comment by L1-M1ng** [comment]
我跟踪到错误代码行，发现推理过程中，当前的q k v都是这个维度：
![image](https://github.com/luchangli03/export_llama_to_onnx/assets/54474696/d5e800d5-9875-4f84-b727-7aa183c83453)
但是传入的past qkv的维度却是这个维度：
![image](https://github.com/luchangli03/export_llama_to_onnx/assets/54474696/992f1eaf-fe60-4bfd-bc1c-c2a486772896)
这种错误应该如何修改呢？

**Comment by L1-M1ng** [comment]
我发现错误是由于我开了"use_cache_quantization"，在我把他关闭后就成功转换出模型了，谢谢！
